server:
  port: 8080

# nohup java -jar -Dspring.profiles.active=prod manager-0.0.1-SNAPSHOT.jar > manager.log &

spring:
  application:
    name: manager
  profiles:
    active: default
  servlet:
  #multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...
    url: jdbc:mysql://mysql-1.caystvcfqph4.ap-northeast-2.rds.amazonaws.com/manager?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # 데이터처리할 대 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성     
  redis:
    host: 127.0.0.1
    port: 6379

# 추가적인 속성
api:
  base-path: http://localhost:8080

eureka:
  client:
    service-url:
    # 유레카 서버의 주소를 작성
      default-zone: http://localhost:8761/eureka/
  instance:
  # 클라이언트 주소 (자기자신 서비스의 포스트명 ip addr, domain name)
  # AWS에서는 hostname: 퍼블릭IP 써야됨
    hostname: localhost
    
#prod 프로필
---
spring:
  profiles: prod
  redis:
    host: 15.164.98.35
    port: 6379
    password: foobared  
  
api:
  base-path: http://ec2-15-164-98-35.ap-northeast-2.compute.amazonaws.com:8080/