server:
  port: 8080

# nohup java -jar -Dspring.profiles.active=prod manager-0.0.1-SNAPSHOT.jar > manager.log &

spring:
  rabbitmq:
    host: ec2-13-124-221-31.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
  application:
    name: manager
  profiles:
    active: default
  servlet:
  # nohup java -jar -Dspring.profiles.active=prod mongyangAnimal-0.0.1-SNAPSHOT.jar > mongyangAnimal.log &
  # multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...
    url: jdbc:mysql://mysql-1.caystvcfqph4.ap-northeast-2.rds.amazonaws.com/manager?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # 데이터처리할 대 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 데이터베이스 객체 생성     
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size=5
        order_inserts: true
        order_updates: true
#  redis:
#    host: 127.0.0.1
#    port: 6379


eureka:
  client:
    serviceUrl:
    # 유레카 서버의 주소를 작성
      defaultZone: http://192.168.0.28:8761/eureka/
  instance:
  # 클라이언트 주소 (자기자신 서비스의 포스트명 ip addr, domain name)
  # AWS에서는 hostname: 퍼블릭IP 써야됨
    hostname: 192.168.0.27
 
# 추가적인 속성
api:
  base-path: http://localhost:8080
     
#prod 프로필
---
spring:
  profiles: prod
  # redis:
    # host: 15.164.98.35
    # port: 6379
    # password: foobared  
  
# api:
  # base-path: http://ec2-15-164-98-35.ap-northeast-2.compute.amazonaws.com:8080/
    
eureka:
  client:
    service-url:
      # 유레카의 ec2 주소
      default-zone: http://13.124.190.225:8761/eureka/
  instance:
    # 본인 서비스의 ec2 주소
    hostname: ec2-15-164-98-35.ap-northeast-2.compute.amazonaws.com